version: 0.0
os: linux
files:
  - source: recipes
    destination: /usr/apps/recipes/recipes
  - source: requirements.txt
    destination: /usr/apps/recipes
  - source: html/index.html
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
  BeforeInstall:
    - location: scripts/before_install.sh
    - location: scripts/set_env.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/application_start.sh
  ValidateService:
    - location: scripts/validate_service.sh