version: 0.0
os: linux
files:
  - source: recipes
    destination: /usr/apps/recipes/recipes
  - source: migrations
    destination: /usr/apps/recipes/migrations
  - source: requirements.txt
    destination: /usr/apps/recipes
  - source: frontend/build
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
  BeforeInstall:
    - location: scripts/before_install.sh
  AfterInstall:
    - location: scripts/after_install.sh
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh